
Artist.create!([
  {name: "Chance The Rapper", city: "Chicago", state: "IL"},
  {name: "Travis Scott", city: "Houston", state: "TX"},
  {name: "Rihanna", city: "St Michael", state: "Barbados"},
  {name: "Vince Staples", city: "Long Beach", state: "CA"},
  {name: "The Underachievers", city: "New York City", state: "NY"},
  {name: "Isaiah Rashad", city: "Chattanooga", state: "TN"},
  {name: "Vic Mensa", city: "Chicago", state: "IL"},
  {name: "clipping.", city: "Los Angeles", state: "CA"},
  {name: "Mick Jenkins", city: "Chicago", state: "IL"},
  {name: "Playboi Carti", city: "Atlanta", state: "GA"},
  {name: "Big K.R.I.T", city: "Meridian", state: "MS"},
  {name: "Father", city: "Atlanta", state: "GA"},
  {name: "Sampha", city: "London", state: "United Kingdom"},
  {name: "21 Savage", city: "Atlanta", state: "GA"},
  {name: "Schoolboy Q", city: "Los Angeles", state: "CA"},
  {name: "Chief Keef", city: "Chicago", state: "IL"},
  {name: "SD", city: "Chicago", state: "IL"},
  {name: "Spooky Black", city: "St Paul", state: "MN"},
  {name: "Mac Miller", city: "Pittsburgh", state: "PA"},
  {name: "Bones", city: "Muir Beach", state: "CA"}
])

MusicVideo.create!([
  {title: "Juice", year: "2013", link: "https://www.youtube.com/watch?v=h8nIHZ-0kS4", featuring: "", youtube_id: "h8nIHZ-0kS4", artist_id: 10},
  {title: "Antidote", year: "2015", link: "https://www.youtube.com/watch?v=KnZ8h3MRuYg", featuring: "", youtube_id: "KnZ8h3MRuYg", artist_id: 11},
  {title: "Work", year: "2016", link: "https://www.youtube.com/watch?v=HL1UzIK-flA", featuring: "Drake", youtube_id: "HL1UzIK-flA", artist_id: 12},
  {title: "Señorita", year: "2015", link: "https://www.youtube.com/watch?v=5OAYMMod9Wo", featuring: "", youtube_id: "5OAYMMod9Wo", artist_id: 13},
  {title: "Star Signs / GENERATION Z", year: "2015", link: "https://www.youtube.com/watch?v=IDhnEJ1WPqE", featuring: "", youtube_id: "IDhnEJ1WPqE", artist_id: 14},
  {title: "4r Da Squaw", year: "2016", link: "https://www.youtube.com/watch?v=nppKPgdc_u0", featuring: "", youtube_id: "nppKPgdc_u0", artist_id: 15},
  {title: "Work Work", year: "2014", link: "https://www.youtube.com/watch?v=-2GozE6XEqg", featuring: "Cocc Pistol Cree", youtube_id: "-2GozE6XEqg", artist_id: 16},
  {title: "Down On My Luck", year: "2014", link: "https://www.youtube.com/watch?v=5jUGAVUwhRU&index=9&list=RDFeJ5bhvvuoM", featuring: "", youtube_id: "5jUGAVUwhRU", artist_id: 17},
  {title: "Dehydration", year: "2014", link: "https://www.youtube.com/watch?v=7TY6YZGAu-k", featuring: "theMIND", youtube_id: "7TY6YZGAu-k", artist_id: 18},
  {title: "Broke Boi", year: "2015", link: "https://www.youtube.com/watch?v=3XOETXVL424", featuring: "", youtube_id: "3XOETXVL424", artist_id: 19},
  {title: "Mt. Olympus", year: "2014", link: "https://www.youtube.com/watch?v=3s-w-zSbTu8&index=27&list=RDCO8pcqxSYJY", featuring: "", youtube_id: "3s-w-zSbTu8", artist_id: 20},
  {title: "Look At Wrist", year: "2014", link: "https://www.youtube.com/watch?v=mF9kOkRCnyo", featuring: "iLoveMakonnen & Key!", youtube_id: "mF9kOkRCnyo", artist_id: 21},
  {title: "Plastic 100°C", year: "2016", link: "https://www.youtube.com/watch?v=kyei9tuS_M8", featuring: "", youtube_id: "kyei9tuS_M8", artist_id: 22},
  {title: "Air It Out", year: "2015", link: "https://www.youtube.com/watch?v=3IBe1v9Ah_I", featuring: "Young Nudy", youtube_id: "3IBe1v9Ah_I", artist_id: 23},
  {title: "Tookie Knows II: Part (2)", year: "2016", link: "https://www.youtube.com/watch?v=YSb6-ppf7fw", featuring: "", youtube_id: "YSb6-ppf7fw", artist_id: 24},
  {title: "Citgo", year: "2013", link: "https://www.youtube.com/watch?v=FE5rpTDoUx0", featuring: "", youtube_id: "FE5rpTDoUx0", artist_id: 25},
  {title: "Circles", year: "2014", link: "https://www.youtube.com/watch?v=XAaGD3PEFZ8", featuring: "", youtube_id: "XAaGD3PEFZ8", artist_id: 26},
  {title: "Without You", year: "2014", link: "https://www.youtube.com/watch?v=_nZfHt5G6UQ", featuring: "", youtube_id: "_nZfHt5G6UQ", artist_id: 27},
  {title: "Watching Movies", year: "2013", link: "https://www.youtube.com/watch?v=wdaI7F3Jv5M", featuring: "", youtube_id: "wdaI7F3Jv5M", artist_id: 28},
  {title: "鈍ら墓地", year: "2013", link: "https://www.youtube.com/watch?v=SFGfUOnsqEw", featuring: "Xavier Wulf", youtube_id: "SFGfUOnsqEw", artist_id: 29}
])
