Artist.create!([
  {name: "Da$H", city: "Hackensack", state: "NJ", vibe: "punk"},
  {name: "Vince Staples", city: "Long Beach", state: "CA", vibe: "punk"},
  {name: "Goldlink", city: "Washington DC", state: "DC", vibe: "soul"},
  {name: "Lil B", city: "Berkeley", state: "CA", vibe: "punk"},
  {name: "Lucki Eck$", city: "Chicago", state: "IL", vibe: "punk"},
  {name: "A$AP Rocky", city: "New York", state: "NY", vibe: "chill"},
  {name: "Joey Bada$$", city: "New York", state: "NY", vibe: "chill"},
  {name: "Action Bronson", city: "New York", state: "NY", vibe: "chill"},
  {name: "G Herbo", city: "Chicago", state: "IL", vibe: "thug"},
  {name: "Waldo", city: "Grand Rapids", state: "MI", vibe: "chill"},
  {name: "Mic Vic", city: "Chicago", state: "IL", vibe: "chill"},
  {name: "Boogie", city: "Compton", state: "California", vibe: "thug"},
  {name: "2 Chainz", city: "Atlanta", state: "GA", vibe: "thump"},
  {name: "21 Savage", city: "Atlanta", state: "GA", vibe: "thug"},
  {name: "Father", city: "Atlanta", state: "GA", vibe: "wavy"},
  {name: "ABRA", city: "Atlanta", state: "GA", vibe: "soul"},
  {name: "Denzel Curry", city: "Miami", state: "FL", vibe: "punk"},
  {name: "Isaiah Rashad", city: "Chattanooga", state: "TN", vibe: "chill"},
  {name: "Chance The Rapper", city: "Chicago", state: "IL", vibe: "soul"},
  {name: "Chief Keef", city: "Chicago", state: "IL", vibe: "thug"},
  {name: "SD", city: "Chicago", state: "IL", vibe: "thug"},
  {name: "Mick Jenkins", city: "Chicago", state: "IL", vibe: "soul"},
  {name: "Young Greatness", city: "New Orleans", state: "LA", vibe: "thump"},
  {name: "Boldy James", city: "Detroit", state: "MI", vibe: "chill"},
  {name: "Travis Scott", city: "Houston", state: "TX", vibe: "wavy"},
  {name: "FKA twigs", city: "London", state: "United Kingdom", vibe: "soul"},
  {name: "Sampha", city: "London", state: "United Kingdom", vibe: "soul"},
  {name: "ScHoolboy Q", city: "Los Angeles", state: "CA", vibe: "thug"},
  {name: "The Underachievers", city: "New York", state: "NY", vibe: "wavy"},
  {name: "clipping.", city: "Los Angeles", state: "CA", vibe: "wavy"},
  {name: "Mac Miller", city: "Pittsburgh", state: "PA", vibe: "wavy"},
  {name: "Jerreau", city: "Columbus", state: "OH", vibe: "chill"},
  {name: "Big K.R.I.T", city: "Meridian", state: "MS", vibe: "soul"},
  {name: "Anderson .Paak", city: "Los Angeles", state: "CA", vibe: "soul"},
  {name: "Black Atlas", city: "Ontario", state: "Canada", vibe: "soul"},
  {name: "Tunji Ige", city: "Philadelphia", state: "PA", vibe: "chill"},
  {name: "Chynna", city: "Philadelphia", state: "PA", vibe: "thug"},
  {name: "Spooky Black", city: "St Paul", state: "MN", vibe: "soul"},
  {name: "KeithCharles Spacebar", city: "Atlanta", state: "GA", vibe: "wavy"},
  {name: "Quentin Miller", city: "Atlanta", state: "GA", vibe: "wavy"},
  {name: "Dumbfoundead", city: "Los Angeles", state: "CA", vibe: "chill"},
  {name: "Aminé", city: "Portland", state: "OR", vibe: "thump"},
  {name: "Tate Kobang", city: "Baltimore", state: "MD", vibe: "thump"},
  {name: "Ty Dolla $ign", city: "Los Angeles", state: "CA", vibe: "pop"},
  {name: "Kelela", city: "Washington DC", state: "DC", vibe: "soul"},
  {name: "Kodak Black", city: "Pompano Beach", state: "FL", vibe: "thug"},
  {name: "Mr. Muthafuckin' eXquire", city: "New York", state: "NY", vibe: "punk"},
  {name: "Robb Bank$", city: "Miami", state: "FL", vibe: "wavy"},
  {name: "Danny Brown", city: "Detroit", state: "MI", vibe: "punk"},
  {name: "Ab-Soul", city: "Los Angeles", state: "CA", vibe: "chill"},
  {name: "Kendrick Lamar", city: "Compton", state: "CA", vibe: "soul"},
  {name: "Bones", city: "San Francisco", state: "CA", vibe: "wavy"},
  {name: "Sage The Gemini", city: "Fairfield", state: "CA", vibe: "pop"},
  {name: "Cousin Stizz", city: "Boston", state: "MA", vibe: "thug"},
  {name: "A$AP Twelvyy", city: "New York", state: "NY", vibe: "chill"},
  {name: "Azealia Banks", city: "New York", state: "NY", vibe: "thump"},
  {name: "RetcH", city: "Hackensack", state: "NJ", vibe: "thug"},
  {name: "Yung Simmie", city: "Miami", state: "FL", vibe: "thug"},
  {name: "IndigoChildRick", city: "Miami", state: "FL", vibe: "wavy"},
  {name: "Maxo Kream", city: "Houston", state: "TX", vibe: "thump"},
  {name: "Dom Kennedy", city: "Los Angeles", state: "CA", vibe: "chill"},
  {name: "Drake", city: "Toronto", state: "Canada", vibe: "pop"},
  {name: "Rihanna", city: "St Michael", state: "Barbados", vibe: "pop"},
  {name: "Usher", city: "Chattanooga", state: "TN", vibe: "pop"},
  {name: "Earl Sweatshirt", city: "Los Angeles", state: "CA", vibe: "punk"},
  {name: "Skeme", city: "Inglewood", state: "CA", vibe: "thug"},
  {name: "Cozz", city: "Los Angeles", state: "CA", vibe: "chill"},
  {name: "The Game", city: "Compton", state: "CA", vibe: "thug"},
  {name: "Pusha T", city: "Virgina Beach", state: "VA", vibe: "chill"},
  {name: "Tyler, The Creator", city: "Los Angeles", state: "CA", vibe: "punk"},
  {name: "Roy Woods", city: "Toronto", state: "Canada", vibe: "soul"},
  {name: "Key!", city: "Atlanta", state: "GA", vibe: "wavy"},
  {name: "Fetty Wap", city: "Paterson", state: "NJ", vibe: "pop"},
  {name: "A$AP Ferg", city: "New York", state: "NY", vibe: "thump"},
  {name: "Kweku Collins", city: "Evanston", state: "IL", vibe: "chill"},
  {name: "Zebra Katz", city: "New York", state: "NY", vibe: "wavy"},
  {name: "Die Antwoord", city: "Cape Town", state: "South Africa", vibe: "punk"},
  {name: "Cakes Da Killa", city: "New York", state: "NY", vibe: "wavy"},
  {name: "Le1f", city: "New York", state: "NY", vibe: "pop"},
  {name: "Jorja Smith", city: "Birmingham", state: "United Kingdom", vibe: "soul"},
  {name: "Blood Orange", city: "London", state: "United Kingdom", vibe: "pop"},
  {name: "Vic Mensa", city: "Chicago", state: "IL", vibe: "thump"},
  {name: "J. Cole", city: "Fayetteville", state: "NC", vibe: "word"},
  {name: "Playboi Carti", city: "Atlanta", state: "GA", vibe: "thump"},
  {name: "Bas", city: "New York", state: "NY", vibe: "word"},
  {name: "Hawk House", city: "London", state: "United Kingdom", vibe: "word"},
  {name: "Oddisee", city: "Washington DC", state: "DC", vibe: "word"},
  {name: "Junglepussy", city: "New York", state: "NY", vibe: "punk"},
  {name: "Chris Travis", city: "Memphis", state: "TN", vibe: "wavy"},
  {name: "Jay Rock", city: "Los Angeles", state: "CA", vibe: "thug"},
  {name: "Capital STEEZ", city: "New York", state: "NY", vibe: "word"},
  {name: "Dyme-A-Duzin", city: "New York", state: "NY", vibe: "chill"},
  {name: "King Louie", city: "Chicago", state: "IL", vibe: "thug"},
  {name: "Ratking", city: "New York", state: "NY", vibe: "punk"},
  {name: "Towkio", city: "Towkio", state: "IL", vibe: "chill"},
  {name: "Raury", city: "Atlanta", state: "GA", vibe: "soul"},
  {name: "Flatbush Zombies", city: "New York", state: "NY", vibe: "wavy"},
  {name: "RiFF RAFF", city: "Houston", state: "TX", vibe: "punk"},
  {name: "Childish Gambino", city: "Atlanta", state: "GA", vibe: "pop"},
  {name: "Ana Tijoux", city: "Santiago", state: "Chile", vibe: "pop"}
])
MusicVideo.create!([
  {title: "Gas Pedal", year: "2013", link: "https://www.youtube.com/watch?v=X8LUd51IuiA", featuring: "IamSu", youtube_id: "X8LUd51IuiA", artist_id: 77, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Jay Reed", year: "2013", link: "https://www.youtube.com/watch?v=W7nweEm2ZOc", featuring: "Da$H", youtube_id: "W7nweEm2ZOc", artist_id: 78, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Glowed Up", year: "2016", link: "https://www.youtube.com/watch?v=yaWesK-nWts", featuring: "", youtube_id: "yaWesK-nWts", artist_id: 39, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "JoHn Muir", year: "2016", link: "https://www.youtube.com/watch?v=Iuq9XK6tojs", featuring: "", youtube_id: "Iuq9XK6tojs", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "My Type Of Party", year: "2012", link: "https://www.youtube.com/watch?v=otHTW_jR1Z0", featuring: "", youtube_id: "otHTW_jR1Z0", artist_id: 79, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Don't Play", year: "2014", link: "https://www.youtube.com/watch?v=iQhLccjeHYI", featuring: "Big Sean", youtube_id: "iQhLccjeHYI", artist_id: 11, featuring_2: "The 1975", featuring_3: "", featuring_4: ""},
  {title: "Lit", year: "2014", link: "https://www.youtube.com/watch?v=WCWubSL5LeE", featuring: "J. Cole", youtube_id: "WCWubSL5LeE", artist_id: 82, featuring_2: "KQuick", featuring_3: "", featuring_4: ""},
  {title: "Right Direction", year: "2016", link: "https://www.youtube.com/watch?v=SBW_fWAZNik", featuring: "", youtube_id: "SBW_fWAZNik", artist_id: 88, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "My Way", year: "2015", link: "https://www.youtube.com/watch?v=YS-5oD2Y4Wk", featuring: "Monty", youtube_id: "YS-5oD2Y4Wk", artist_id: 89, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Moolah", year: "2016", link: "https://www.youtube.com/watch?v=dAFiZFepEz8", featuring: "", youtube_id: "dAFiZFepEz8", artist_id: 90, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Wut", year: "2012", link: "https://www.youtube.com/watch?v=Nrnq4SZ0luc", featuring: "", youtube_id: "Nrnq4SZ0luc", artist_id: 95, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Liquorice ", year: "2012", link: "https://www.youtube.com/watch?v=ZlWRhnYgWcc", featuring: "", youtube_id: "ZlWRhnYgWcc", artist_id: 98, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Baby;s On Fire", year: "2012", link: "https://www.youtube.com/watch?v=HcXNPI-IPPM", featuring: "", youtube_id: "HcXNPI-IPPM", artist_id: 99, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Tidal Tendencies", year: "2013", link: "https://www.youtube.com/watch?v=mhOkRfhmwCk", featuring: "", youtube_id: "mhOkRfhmwCk", artist_id: 106, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Where Did I Go?", year: "2016", link: "https://www.youtube.com/watch?v=meP1neJrguw", featuring: "", youtube_id: "meP1neJrguw", artist_id: 108, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Money Trees Deuce", year: "2015", link: "https://www.youtube.com/watch?v=fk10RoZV4fw", featuring: "", youtube_id: "fk10RoZV4fw", artist_id: 112, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Survival Tactics", year: "2012", link: "https://www.youtube.com/watch?v=DDWAk8-leVA", featuring: "Capital STEEZ", youtube_id: "DDWAk8-leVA", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Free The Robots", year: "2012", link: "https://www.youtube.com/watch?v=XcmR8DxuHBA", featuring: "", youtube_id: "XcmR8DxuHBA", artist_id: 113, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "When It Rain", year: "2016", link: "https://www.youtube.com/watch?v=LVyGxlgeAjc", featuring: "", youtube_id: "LVyGxlgeAjc", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "3005", year: "2013", link: "https://www.youtube.com/watch?v=tG35R8F2j8k", featuring: "", youtube_id: "tG35R8F2j8k", artist_id: 121, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Look At Wrist", year: "2014", link: "https://www.youtube.com/watch?v=mF9kOkRCnyo", featuring: "iLoveMakonnen", youtube_id: "mF9kOkRCnyo", artist_id: 21, featuring_2: "Key!", featuring_3: "", featuring_4: ""},
  {title: "Red Nose", year: "2013", link: "https://www.youtube.com/watch?v=-I-YY5p0uq8", featuring: "", youtube_id: "-I-YY5p0uq8", artist_id: 77, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Brighton Beach", year: "2013", link: "https://www.youtube.com/watch?v=wmCgTiORAvg", featuring: "", youtube_id: "wmCgTiORAvg", artist_id: 63, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Glock Rivers", year: "2014", link: "https://www.youtube.com/watch?v=XY7WFUq4EKU", featuring: "", youtube_id: "XY7WFUq4EKU", artist_id: 78, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "After School", year: "2014", link: "https://www.youtube.com/watch?v=gPzx06MjSvc", featuring: "", youtube_id: "gPzx06MjSvc", artist_id: 79, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Ain't Perfect", year: "2013", link: "https://www.youtube.com/watch?v=JoV-AyBn3oY", featuring: "Wale", youtube_id: "JoV-AyBn3oY", artist_id: 80, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "I Need That", year: "2015", link: "https://www.youtube.com/watch?v=6ljqfW1VLTY", featuring: "Bas", youtube_id: "6ljqfW1VLTY", artist_id: 81, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Mook In New Mexico", year: "2014", link: "https://www.youtube.com/watch?v=g-y_0Zk385E", featuring: "", youtube_id: "g-y_0Zk385E", artist_id: 82, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Nosetalgia", year: "2013", link: "https://www.youtube.com/watch?v=u-2ckLBV21g", featuring: "Kendrick Lamar", youtube_id: "u-2ckLBV21g", artist_id: 84, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "IFHY", year: "2013", link: "https://www.youtube.com/watch?v=3lDqMx4rmFU", featuring: "", youtube_id: "3lDqMx4rmFU", artist_id: 85, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Higher", year: "2014", link: "https://www.youtube.com/watch?v=0LqBw6FNNng", featuring: "SBTRKT", youtube_id: "0LqBw6FNNng", artist_id: 86, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "100 Bricks", year: "2015", link: "https://www.youtube.com/watch?v=JnfjYz_QxSg", featuring: "", youtube_id: "JnfjYz_QxSg", artist_id: 90, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Wavvy", year: "2012", link: "https://www.youtube.com/watch?v=sokeAMDm7mk", featuring: "", youtube_id: "sokeAMDm7mk", artist_id: 96, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "LST CTRL", year: "2013", link: "https://www.youtube.com/watch?v=f-JdoWgf-y4", featuring: "", youtube_id: "f-JdoWgf-y4", artist_id: 97, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "212", year: "2011", link: "https://www.youtube.com/watch?v=i3Jv9fNPjgk", featuring: "Lazy Jay", youtube_id: "i3Jv9fNPjgk", artist_id: 98, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Banana Brain", year: "2016", link: "https://www.youtube.com/watch?v=XXlZfc1TrD0", featuring: "", youtube_id: "XXlZfc1TrD0", artist_id: 99, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Own Appeal", year: "2013", link: "https://www.youtube.com/watch?v=E2Snh2NZHhk", featuring: "", youtube_id: "E2Snh2NZHhk", artist_id: 107, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "First Step", year: "2014", link: "https://www.youtube.com/watch?v=88GN9r9KuNg&list=RDUkmE7JHWV-U&index=4", featuring: "yU", youtube_id: "88GN9r9KuNg", artist_id: 107, featuring_2: "Uptown XO", featuring_3: "", featuring_4: ""},
  {title: "Crooked Smile", year: "2013", link: "https://www.youtube.com/watch?v=fzzMOMkjm8A", featuring: "TLC", youtube_id: "fzzMOMkjm8A", artist_id: 110, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Without You", year: "2014", link: "https://www.youtube.com/watch?v=_nZfHt5G6UQ", featuring: "", youtube_id: "_nZfHt5G6UQ", artist_id: 27, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Watching Movies", year: "2013", link: "https://www.youtube.com/watch?v=wdaI7F3Jv5M", featuring: "", youtube_id: "wdaI7F3Jv5M", artist_id: 28, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "I Shot You Down", year: "2013", link: "https://www.youtube.com/watch?v=vUaqIoXGVV4", featuring: "", youtube_id: "vUaqIoXGVV4", artist_id: 15, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "鈍ら墓地", year: "2013", link: "https://www.youtube.com/watch?v=SFGfUOnsqEw", featuring: "Xavier Wulf", youtube_id: "SFGfUOnsqEw", artist_id: 29, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Air It Out", year: "2015", link: "https://www.youtube.com/watch?v=3IBe1v9Ah_I", featuring: "Young Nudy", youtube_id: "3IBe1v9Ah_I", artist_id: 23, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Paper Trail$", year: "2015", link: "https://www.youtube.com/watch?v=stoLqWXsIOY", featuring: "", youtube_id: "stoLqWXsIOY", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Yammy Gang", year: "2016", link: "https://www.youtube.com/watch?v=MQvb_oGWzgk", featuring: "A$AP Mob & Tatiana ", youtube_id: "MQvb_oGWzgk", artist_id: 30, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Sober", year: "2015", link: "https://www.youtube.com/watch?v=jx96Twg-Aew", featuring: "", youtube_id: "jx96Twg-Aew", artist_id: 121, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "No Bells", year: "2015", link: "https://www.youtube.com/watch?v=qa-vY5skAGs", featuring: "", youtube_id: "qa-vY5skAGs", artist_id: 34, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Say Wassup", year: "2011", link: "https://www.youtube.com/watch?v=UziocaSimyc", featuring: "Ab-Soul", youtube_id: "UziocaSimyc", artist_id: 112, featuring_2: "ScHoolboy Q", featuring_3: "Kendrick Lamar", featuring_4: ""},
  {title: "Day2Day (Remix)", year: "2014", link: "https://www.youtube.com/watch?v=XREugU4qTB4", featuring: "Michael Christmas & ILoveMakonnen", youtube_id: "XREugU4qTB4", artist_id: 35, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "On My Grind", year: "2016", link: "https://www.youtube.com/watch?v=zggKgEWJmSI", featuring: "", youtube_id: "zggKgEWJmSI", artist_id: 35, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "OnMy Grind", year: "2016", link: "https://www.youtube.com/watch?v=zggKgEWJmSI", featuring: "", youtube_id: "zggKgEWJmSI", artist_id: 35, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Juice", year: "2013", link: "https://www.youtube.com/watch?v=h8nIHZ-0kS4", featuring: "", youtube_id: "h8nIHZ-0kS4", artist_id: 10, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Antidote", year: "2015", link: "https://www.youtube.com/watch?v=KnZ8h3MRuYg", featuring: "", youtube_id: "KnZ8h3MRuYg", artist_id: 11, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Work", year: "2016", link: "https://www.youtube.com/watch?v=HL1UzIK-flA", featuring: "Drake", youtube_id: "HL1UzIK-flA", artist_id: 12, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Throw Dem Gunz", year: "2013", link: "https://www.youtube.com/watch?v=t99r8JSdI7s", featuring: "", youtube_id: "t99r8JSdI7s", artist_id: 47, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Threatz", year: "2013", link: "https://www.youtube.com/watch?v=vwnVI_x5g0I", featuring: "Yung Simmie & Robb Bank$", youtube_id: "vwnVI_x5g0I", artist_id: 38, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Caroline", year: "2016", link: "https://www.youtube.com/watch?v=3j8ecF8Wt4E", featuring: "", youtube_id: "3j8ecF8Wt4E", artist_id: 93, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "L.Y.B.B. (Resolution)", year: "2016", link: "https://www.youtube.com/watch?v=bmaLgwy8DQI", featuring: "", youtube_id: "bmaLgwy8DQI", artist_id: 78, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "If It Don't Make Money", year: "2014", link: "https://www.youtube.com/watch?v=q43NiWcvSwA", featuring: "Skeme", youtube_id: "q43NiWcvSwA", artist_id: 79, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Mamicita", year: "2014", link: "https://www.youtube.com/watch?v=RH9kl6XZixo", featuring: "Rich Homie Quan", youtube_id: "RH9kl6XZixo", artist_id: 11, featuring_2: "Young Thug", featuring_3: "", featuring_4: ""},
  {title: "Dreams", year: "2014", link: "https://www.youtube.com/watch?v=i8Dg6qj8L3M", featuring: "", youtube_id: "i8Dg6qj8L3M", artist_id: 81, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Night Job", year: "2016", link: "https://www.youtube.com/watch?v=70x4yfWpLb0", featuring: "J. Cole", youtube_id: "70x4yfWpLb0", artist_id: 82, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Numbers On The Boards", year: "2013", link: "https://www.youtube.com/watch?v=DawrlSwHUiM", featuring: "", youtube_id: "DawrlSwHUiM", artist_id: 84, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "What The Fuck Right Now", year: "2016", link: "https://www.youtube.com/watch?v=oCd6SQ67k-Y", featuring: "", youtube_id: "oCd6SQ67k-Y", artist_id: 85, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "When I Die", year: "2014", link: "https://www.youtube.com/watch?v=FeJ5bhvvuoM", featuring: "", youtube_id: "FeJ5bhvvuoM", artist_id: 91, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Wassup", year: "2015", link: "https://www.youtube.com/watch?v=F5rrJA8es90", featuring: "", youtube_id: "F5rrJA8es90", artist_id: 91, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Really Got It", year: "2016", link: "https://www.youtube.com/watch?v=dzt4yEuFWAM", featuring: "", youtube_id: "dzt4yEuFWAM", artist_id: 92, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Tear The House Up", year: "2014", link: "https://www.youtube.com/watch?v=m5By5X6sl_U", featuring: "Hervé", youtube_id: "m5By5X6sl_U", artist_id: 97, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Wallace", year: "2015", link: "https://www.youtube.com/watch?v=ew_sKPeF5iU", featuring: "", youtube_id: "ew_sKPeF5iU", artist_id: 98, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Power Trip", year: "2013", link: "https://www.youtube.com/watch?v=7AjD7nKiUQ4", featuring: "Miguel", youtube_id: "7AjD7nKiUQ4", artist_id: 110, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Like Me", year: "2015", link: "https://www.youtube.com/watch?v=Nr_Gzz6ZRaE", featuring: "BJ the Chicago Kid", youtube_id: "Nr_Gzz6ZRaE", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Telegraph Ave (\"Oakland\" by Lloyd) ", year: "2014", link: "https://www.youtube.com/watch?v=p3f-eDzkxcw", featuring: "", youtube_id: "p3f-eDzkxcw", artist_id: 121, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Vice City", year: "2015", link: "https://www.youtube.com/watch?v=Jug2HZ3dkoc", featuring: "Ab-Soul", youtube_id: "Jug2HZ3dkoc", artist_id: 112, featuring_2: "ScHoolboy Q", featuring_3: "Kendrick Lamar", featuring_4: ""},
  {title: "Señorita", year: "2015", link: "https://www.youtube.com/watch?v=5OAYMMod9Wo", featuring: "", youtube_id: "5OAYMMod9Wo", artist_id: 13, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Star Signs / GENERATION Z", year: "2015", link: "https://www.youtube.com/watch?v=IDhnEJ1WPqE", featuring: "", youtube_id: "IDhnEJ1WPqE", artist_id: 14, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "4r Da Squaw", year: "2016", link: "https://www.youtube.com/watch?v=nppKPgdc_u0", featuring: "", youtube_id: "nppKPgdc_u0", artist_id: 15, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Dehydration", year: "2014", link: "https://www.youtube.com/watch?v=7TY6YZGAu-k", featuring: "theMIND", youtube_id: "7TY6YZGAu-k", artist_id: 18, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Mt. Olympus", year: "2014", link: "https://www.youtube.com/watch?v=3s-w-zSbTu8&index=27&list=RDCO8pcqxSYJY", featuring: "", youtube_id: "3s-w-zSbTu8", artist_id: 20, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Plastic 100°C", year: "2016", link: "https://www.youtube.com/watch?v=kyei9tuS_M8", featuring: "", youtube_id: "kyei9tuS_M8", artist_id: 22, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Tookie Knows II: Part (2)", year: "2016", link: "https://www.youtube.com/watch?v=YSb6-ppf7fw", featuring: "", youtube_id: "YSb6-ppf7fw", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Citgo", year: "2013", link: "https://www.youtube.com/watch?v=FE5rpTDoUx0", featuring: "", youtube_id: "FE5rpTDoUx0", artist_id: 25, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Circles", year: "2014", link: "https://www.youtube.com/watch?v=XAaGD3PEFZ8", featuring: "", youtube_id: "XAaGD3PEFZ8", artist_id: 26, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "On My Grind", year: "2016", link: "https://www.youtube.com/watch?v=zggKgEWJmSI", featuring: "", youtube_id: "zggKgEWJmSI", artist_id: 36, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Day2Day (Remix)", year: "2014", link: "https://www.youtube.com/watch?v=XREugU4qTB4", featuring: "Michael Christmas & ILoveMakonnen", youtube_id: "XREugU4qTB4", artist_id: 36, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Free Lunch", year: "2016", link: "https://www.youtube.com/watch?v=QJksTRgY8-c", featuring: "", youtube_id: "QJksTRgY8-c", artist_id: 15, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "The Conversation", year: "2015", link: "https://www.youtube.com/watch?v=V0A1dJxTJzE", featuring: "", youtube_id: "V0A1dJxTJzE", artist_id: 41, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Work work", year: "2014", link: "https://www.youtube.com/watch?v=-2GozE6XEqg", featuring: "Cocc Pistol Cree", youtube_id: "-2GozE6XEqg", artist_id: 17, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Glen Coco", year: "2014", link: "https://www.youtube.com/watch?v=SDXTQqCQpfY", featuring: "", youtube_id: "SDXTQqCQpfY", artist_id: 41, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Down On My Luck", year: "2014", link: "https://www.youtube.com/watch?v=5jUGAVUwhRU", featuring: "", youtube_id: "5jUGAVUwhRU", artist_id: 16, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Yammy Gang", year: "2013", link: "https://www.youtube.com/watch?v=MQvb_oGWzgk", featuring: "", youtube_id: "MQvb_oGWzgk", artist_id: 33, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Moochie", year: "2013", link: "https://www.youtube.com/watch?v=GGosx170Kdk", featuring: "", youtube_id: "GGosx170Kdk", artist_id: 37, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Parents", year: "2014", link: "https://www.youtube.com/watch?v=kuiwNb-Pxcc", featuring: "", youtube_id: "kuiwNb-Pxcc", artist_id: 38, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "U Mad", year: "2015", link: "https://www.youtube.com/watch?v=fP8FMdVcCQQ", featuring: "Kanye West", youtube_id: "fP8FMdVcCQQ", artist_id: 16, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Water Me", year: "2013", link: "https://www.youtube.com/watch?v=kFtMl-uipA8", featuring: "", youtube_id: "kFtMl-uipA8", artist_id: 43, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Papi Pacify", year: "2013", link: "https://www.youtube.com/watch?v=OydK91JjFOw", featuring: "", youtube_id: "OydK91JjFOw", artist_id: 43, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Two Weeks", year: "2014", link: "https://www.youtube.com/watch?v=3yDP9MKVhZc", featuring: "", youtube_id: "3yDP9MKVhZc", artist_id: 43, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "L$D (LOVE x $EX x DREAMS)", year: "2015", link: "https://www.youtube.com/watch?v=yEG2VTHS9yg", featuring: "", youtube_id: "yEG2VTHS9yg", artist_id: 44, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Feel That", year: "2014", link: "https://www.youtube.com/watch?v=gbcyfRztHmw", featuring: "", youtube_id: "gbcyfRztHmw", artist_id: 16, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Broke Boi", year: "2015", link: "https://www.youtube.com/watch?v=3XOETXVL424", featuring: "", youtube_id: "3XOETXVL424", artist_id: 19, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "B Like", year: "2015", link: "https://www.youtube.com/watch?v=HfsW-aX3ptU", featuring: "", youtube_id: "HfsW-aX3ptU", artist_id: 80, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Housewives", year: "2015", link: "https://www.youtube.com/watch?v=YyALkCHSh_0", featuring: "", youtube_id: "YyALkCHSh_0", artist_id: 82, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "100", year: "2015", link: "https://www.youtube.com/watch?v=b2AcxL88DoI", featuring: "Drake", youtube_id: "b2AcxL88DoI", artist_id: 83, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Sober Thoughts", year: "2015", link: "https://www.youtube.com/watch?v=Nhm87YivsWM", featuring: "", youtube_id: "Nhm87YivsWM", artist_id: 91, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Talkin Greezy", year: "2016", link: "https://www.youtube.com/watch?v=3orspcmY3cU", featuring: "", youtube_id: "3orspcmY3cU", artist_id: 101, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Nah", year: "2014", link: "https://www.youtube.com/watch?v=AtwVdabW0GE", featuring: "", youtube_id: "AtwVdabW0GE", artist_id: 102, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Terrorist Threats", year: "2012", link: "https://www.youtube.com/watch?v=m_71q5lVEjc", featuring: "Danny Brown", youtube_id: "m_71q5lVEjc", artist_id: 49, featuring_2: " Jhene Aiko", featuring_3: "", featuring_4: ""},
  {title: "You're Not Good Enough", year: "2014", link: "https://www.youtube.com/watch?v=7gtdpnKbT10", featuring: "", youtube_id: "7gtdpnKbT10", artist_id: 103, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Black Lite", year: "2016", link: "https://www.youtube.com/watch?v=_ty1sY0stxo", featuring: "", youtube_id: "_ty1sY0stxo", artist_id: 114, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Eastside Shit", year: "2013", link: "https://www.youtube.com/watch?v=8lh4ZN18gCc", featuring: "G Herbo", youtube_id: "8lh4ZN18gCc", artist_id: 115, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Clean Up", year: "2016", link: "https://www.youtube.com/watch?v=WWeVC0K17Ok", featuring: "", youtube_id: "WWeVC0K17Ok", artist_id: 116, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "So Sick Stories", year: "2014", link: "https://www.youtube.com/watch?v=SpBCXWKx4Tg", featuring: "King Krule", youtube_id: "SpBCXWKx4Tg", artist_id: 117, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Cadillactica", year: "2015", link: "https://www.youtube.com/watch?v=kMrCWR1S3Jw", featuring: "", youtube_id: "kMrCWR1S3Jw", artist_id: 20, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "How To Be The Man", year: "2014", link: "https://www.youtube.com/watch?v=biiy1QAZY1s", featuring: "", youtube_id: "biiy1QAZY1s", artist_id: 120, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Sweatpants", year: "2014", link: "https://www.youtube.com/watch?v=ExVtrghW5Y4", featuring: "Problem", youtube_id: "ExVtrghW5Y4", artist_id: 121, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Fruit", year: "2015", link: "https://www.youtube.com/watch?v=CI1g4dnDtao", featuring: "", youtube_id: "CI1g4dnDtao", artist_id: 42, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Needsumbody", year: "2014", link: "https://www.youtube.com/watch?v=wjGnnjZVHPI", featuring: "", youtube_id: "wjGnnjZVHPI", artist_id: 42, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Blossom", year: "2014", link: "https://www.youtube.com/watch?v=QlefEv1IwH0", featuring: "", youtube_id: "QlefEv1IwH0", artist_id: 40, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Energy", year: "2015", link: "https://www.youtube.com/watch?v=7LnBvuzjpr4", featuring: "", youtube_id: "7LnBvuzjpr4", artist_id: 45, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Lift Me Up", year: "2016", link: "https://www.youtube.com/watch?v=bn15IvVrprw", featuring: "", youtube_id: "bn15IvVrprw", artist_id: 13, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "No Limit", year: "2016", link: "https://www.youtube.com/watch?v=3w0yqAdJ1iY", featuring: "Young Thug", youtube_id: "3w0yqAdJ1iY", artist_id: 46, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Zone 3", year: "2014", link: "https://www.youtube.com/watch?v=vQBBLRCQV0w", featuring: "", youtube_id: "vQBBLRCQV0w", artist_id: 38, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Oversick", year: "2013", link: "https://www.youtube.com/watch?v=MsBuLoQNBAY", featuring: "", youtube_id: "MsBuLoQNBAY", artist_id: 80, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "I'm Tha Man", year: "2015", link: "https://www.youtube.com/watch?v=6FdKK6qO6sA", featuring: "", youtube_id: "6FdKK6qO6sA", artist_id: 81, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Martians Vs. Goblins", year: "2011", link: "https://www.youtube.com/watch?v=gODGcVSzh1U", featuring: "Lil Wayne", youtube_id: "gODGcVSzh1U", artist_id: 83, featuring_2: "Tyler, The Creator", featuring_3: "", featuring_4: ""},
  {title: "Untouchable", year: "2015", link: "https://www.youtube.com/watch?v=NPI_6MX74j4", featuring: "", youtube_id: "NPI_6MX74j4", artist_id: 84, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Trap Tears", year: "2015", link: "https://www.youtube.com/watch?v=ynmCgpaArOc", featuring: "Key!", youtube_id: "ynmCgpaArOc", artist_id: 86, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Ay Ay", year: "2014", link: "https://www.youtube.com/watch?v=Q4ULkS88qzQ", featuring: "", youtube_id: "Q4ULkS88qzQ", artist_id: 91, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Time Will Tell", year: "2013", link: "https://www.youtube.com/watch?v=-18J8lGJeLo", featuring: "", youtube_id: "-18J8lGJeLo", artist_id: 103, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "That Chicken", year: "2015", link: "https://www.youtube.com/watch?v=vKtEBUHg06o", featuring: "", youtube_id: "vKtEBUHg06o", artist_id: 114, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "B.O.N.", year: "2014", link: "https://www.youtube.com/watch?v=NHZDQ10WzCc", featuring: "", youtube_id: "NHZDQ10WzCc", artist_id: 115, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Reflection", year: "2015", link: "https://www.youtube.com/watch?v=RPE5Ruj67Sg", featuring: "", youtube_id: "RPE5Ruj67Sg", artist_id: 116, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Canal", year: "2014", link: "https://www.youtube.com/watch?v=uAWzCmkJqpc", featuring: "", youtube_id: "uAWzCmkJqpc", artist_id: 117, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "N.A.S.A. New Age Smokers Anthem", year: "2013", link: "https://www.youtube.com/watch?v=DUvFlKfEgpk", featuring: "", youtube_id: "DUvFlKfEgpk", artist_id: 14, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bird On A Wire", year: "2012", link: "https://www.youtube.com/watch?v=T4IvoJG4HzI", featuring: "Action Bronson", youtube_id: "T4IvoJG4HzI", artist_id: 120, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bend The Bloccs Freestyle", year: "2016", link: "https://www.youtube.com/watch?v=4MVVoJpv72E", featuring: "DeILLest", youtube_id: "4MVVoJpv72E", artist_id: 73, featuring_2: "Cokey Briccz", featuring_3: "", featuring_4: ""},
  {title: "Get You Good", year: "2015", link: "https://www.youtube.com/watch?v=bzefB3CtjnI", featuring: "", youtube_id: "bzefB3CtjnI", artist_id: 87, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Man Of The Year", year: "2014", link: "https://www.youtube.com/watch?v=rEMsjeq43_U", featuring: "", youtube_id: "rEMsjeq43_U", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Chamakay", year: "2013", link: "https://www.youtube.com/watch?v=DfZMvTHJLUs", featuring: "", youtube_id: "DfZMvTHJLUs", artist_id: 103, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Michael Jordan", year: "2013", link: "https://www.youtube.com/watch?v=GIYwtU_B9oI", featuring: "", youtube_id: "GIYwtU_B9oI", artist_id: 115, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Or Nah", year: "2014", link: "https://www.youtube.com/watch?v=TUj0otkJEBo", featuring: "The Weeknd", youtube_id: "TUj0otkJEBo", artist_id: 71, featuring_2: "Wiz Khalifa", featuring_3: "", featuring_4: ""},
  {title: "Red Opps", year: "2015", link: "https://www.youtube.com/watch?v=mWISiHcGoNg", featuring: "", youtube_id: "mWISiHcGoNg", artist_id: 23, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Vamp", year: "2015", link: "https://www.youtube.com/watch?v=KgTHrXIRZG4", featuring: "Tommy Genesis", youtube_id: "KgTHrXIRZG4", artist_id: 21, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Skrilla", year: "2015", link: "https://www.youtube.com/watch?v=SmwmZfMooSo", featuring: "", youtube_id: "SmwmZfMooSo", artist_id: 62, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Seymor", year: "2015", link: "https://www.youtube.com/watch?v=lH_9kEIipb8", featuring: "", youtube_id: "lH_9kEIipb8", artist_id: 63, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Amedei Porcelana", year: "2014", link: "https://www.youtube.com/watch?v=DJaZdw5mMiY", featuring: "", youtube_id: "DJaZdw5mMiY", artist_id: 65, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "4sho", year: "2013", link: "https://www.youtube.com/watch?v=INHA8lg70cI", featuring: "", youtube_id: "INHA8lg70cI", artist_id: 67, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Poppin' Da Trunk", year: "2014", link: "https://www.youtube.com/watch?v=tDtYnth09Xg", featuring: "", youtube_id: "tDtYnth09Xg", artist_id: 67, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Where I Came From", year: "2016", link: "https://www.youtube.com/watch?v=dyXp92l3S5Y", featuring: "", youtube_id: "dyXp92l3S5Y", artist_id: 34, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "The Season / Carry Me / The Waters", year: "2016", link: "https://www.youtube.com/watch?v=y_Ka5wiQBEw", featuring: "", youtube_id: "y_Ka5wiQBEw", artist_id: 39, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Safe", year: "2016", link: "https://www.youtube.com/watch?v=mmvqb9Uzu8k", featuring: "", youtube_id: "mmvqb9Uzu8k", artist_id: 69, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bank Head", year: "2013", link: "https://www.youtube.com/watch?v=6I_2eYvrEJw", featuring: "Kingdom", youtube_id: "6I_2eYvrEJw", artist_id: 72, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Ice Cups", year: "2015", link: "https://www.youtube.com/watch?v=JSBdrCkjXsY", featuring: "Anthony Mason", youtube_id: "JSBdrCkjXsY", artist_id: 73, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "G.A.D.D.", year: "2013", link: "https://www.youtube.com/watch?v=Ngyawk7gfZ8", featuring: "Ran$ah", youtube_id: "Ngyawk7gfZ8", artist_id: 55, featuring_2: "Monster Mike", featuring_3: "", featuring_4: ""},
  {title: "Gwan Big Up Urself", year: "2016", link: "https://www.youtube.com/watch?v=AiPYEpvSaxk", featuring: "", youtube_id: "AiPYEpvSaxk", artist_id: 87, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bank Rolls", year: "2015", link: "https://www.youtube.com/watch?v=i3i2s3JELFs", featuring: "", youtube_id: "i3i2s3JELFs", artist_id: 94, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Ima Read", year: "2012", link: "https://www.youtube.com/watch?v=oo4Sqt2Bmag", featuring: "Njena Reddd Foxxx", youtube_id: "oo4Sqt2Bmag", artist_id: 97, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "1991", year: "2012", link: "https://www.youtube.com/watch?v=0oM_9ca8hxE", featuring: "", youtube_id: "0oM_9ca8hxE", artist_id: 98, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Zef Side", year: "2010", link: "https://www.youtube.com/watch?v=Q77YBmtd2Rw", featuring: "", youtube_id: "Q77YBmtd2Rw", artist_id: 99, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Not Really", year: "2012", link: "https://www.youtube.com/watch?v=yhe-eYHQgXA", featuring: "", youtube_id: "yhe-eYHQgXA", artist_id: 100, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Stupid Rose", year: "2016", link: "https://www.youtube.com/watch?v=nl6OW07A5q4", featuring: "", youtube_id: "nl6OW07A5q4", artist_id: 104, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Phantom", year: "2013", link: "https://www.youtube.com/watch?v=N53zkq_ypoc", featuring: "", youtube_id: "N53zkq_ypoc", artist_id: 105, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Lost Ones", year: "2011", link: "https://www.youtube.com/watch?v=y-vQ_VsTkn0", featuring: "", youtube_id: "y-vQ_VsTkn0", artist_id: 110, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Chill Pill (Experiment 2)", year: "2014", link: "https://www.youtube.com/watch?v=nRRb5Mqr3VE", featuring: "", youtube_id: "nRRb5Mqr3VE", artist_id: 106, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Park", year: "2016", link: "https://www.youtube.com/watch?v=NTJNaR_hPXQ", featuring: "", youtube_id: "NTJNaR_hPXQ", artist_id: 15, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "We Up", year: "2016", link: "https://www.youtube.com/watch?v=FyofwPb0SCE", featuring: "Bones", youtube_id: "FyofwPb0SCE", artist_id: 111, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Acid Rain", year: "2015", link: "https://www.youtube.com/watch?v=nxg4C365LbQ", featuring: "", youtube_id: "nxg4C365LbQ", artist_id: 109, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "My Yout", year: "2013", link: "https://www.youtube.com/watch?v=6OiMq6Rau64", featuring: "", youtube_id: "6OiMq6Rau64", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "World Turning", year: "2013", link: "https://www.youtube.com/watch?v=Rwj389ssZd4", featuring: "Joey Purp", youtube_id: "Rwj389ssZd4", artist_id: 116, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Avian", year: "2014", link: "https://www.youtube.com/watch?v=mFWf4Tb5m6Y", featuring: "", youtube_id: "mFWf4Tb5m6Y", artist_id: 28, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Baby Blue", year: "2015", link: "https://www.youtube.com/watch?v=bVP_w1rQweE", featuring: "Chance The Rapper", youtube_id: "bVP_w1rQweE", artist_id: 50, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Devastated", year: "2016", link: "https://www.youtube.com/watch?v=RLnA25dVzrQ", featuring: "", youtube_id: "RLnA25dVzrQ", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Hardknock", year: "2012", link: "https://www.youtube.com/watch?v=Uv658wfVt6I", featuring: "CJ Fly", youtube_id: "Uv658wfVt6I", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Out", year: "2014", link: "https://www.youtube.com/watch?v=dm1FS5PfzAI", featuring: "", youtube_id: "dm1FS5PfzAI", artist_id: 54, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Potential", year: "2016", link: "https://www.youtube.com/watch?v=cFT30ClRBdg", featuring: "", youtube_id: "cFT30ClRBdg", artist_id: 56, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Royal Oats", year: "2015", link: "https://www.youtube.com/watch?v=CK_ry3doEYc", featuring: "", youtube_id: "CK_ry3doEYc", artist_id: 54, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bitter Raps", year: "2014", link: "https://www.youtube.com/watch?v=XmUgmo7x_sA", featuring: "", youtube_id: "XmUgmo7x_sA", artist_id: 57, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "A Message", year: "2015", link: "https://www.youtube.com/watch?v=m4-9mYrbXVI", featuring: "", youtube_id: "m4-9mYrbXVI", artist_id: 72, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Potential", year: "2016", link: "https://www.youtube.com/watch?v=cFT30ClRBdg", featuring: "", youtube_id: "cFT30ClRBdg", artist_id: 58, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Worst Behavior", year: "2013", link: "https://www.youtube.com/watch?v=CccnAvfLPvE", featuring: "", youtube_id: "CccnAvfLPvE", artist_id: 45, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Drink My Spit", year: "2014", link: "https://www.youtube.com/watch?v=Ifo4y6Ad714", featuring: "", youtube_id: "Ifo4y6Ad714", artist_id: 59, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Combination", year: "2015", link: "https://www.youtube.com/watch?v=kphKtIKYH-o", featuring: "TheCoolisMac", youtube_id: "kphKtIKYH-o", artist_id: 58, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "All The Way Live", year: "2014", link: "https://www.youtube.com/watch?v=tTYCglUYxNg", featuring: "", youtube_id: "tTYCglUYxNg", artist_id: 60, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Grief", year: "2015", link: "https://www.youtube.com/watch?v=tZ5Mu2gs-M8", featuring: "", youtube_id: "tZ5Mu2gs-M8", artist_id: 61, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Off Top", year: "2015", link: "https://www.youtube.com/watch?v=wrxxfrzJY6k", featuring: "", youtube_id: "wrxxfrzJY6k", artist_id: 61, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Chum", year: "2012", link: "https://www.youtube.com/watch?v=FCbWLSZrZfw", featuring: "", youtube_id: "FCbWLSZrZfw", artist_id: 61, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Not Enough Words", year: "2011", link: "https://www.youtube.com/watch?v=n8APYF0kkas", featuring: "Statik Selektah", youtube_id: "n8APYF0kkas", artist_id: 50, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Bitch, Don't Kill My Vibe", year: "2013", link: "https://www.youtube.com/watch?v=GF8aaTu2kg0", featuring: "", youtube_id: "GF8aaTu2kg0", artist_id: 75, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Groovy Tony", year: "2016", link: "https://www.youtube.com/watch?v=7iJDXIOk0bg", featuring: "", youtube_id: "7iJDXIOk0bg", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Alright", year: "2015", link: "https://www.youtube.com/watch?v=Z-48u_uWMHY", featuring: "", youtube_id: "Z-48u_uWMHY", artist_id: 75, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Time", year: "2013", link: "https://www.youtube.com/watch?v=pzAtdu0mslo", featuring: "", youtube_id: "pzAtdu0mslo", artist_id: 120, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Headlines", year: "2011", link: "https://www.youtube.com/watch?v=cimoNqiulUE", featuring: "", youtube_id: "cimoNqiulUE", artist_id: 45, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Gees", year: "2013", link: "https://www.youtube.com/watch?v=1JGmTalfUQY", featuring: "ScHoolboy Q", youtube_id: "1JGmTalfUQY", artist_id: 28, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Gangway", year: "2012", link: "https://www.youtube.com/watch?v=8TqckF87f5Q", featuring: "", youtube_id: "8TqckF87f5Q", artist_id: 51, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Climax", year: "2012", link: "https://www.youtube.com/watch?v=nNTyfVh3nmU", featuring: "", youtube_id: "nNTyfVh3nmU", artist_id: 46, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Possible", year: "2015", link: "https://www.youtube.com/watch?v=eCBSTUS23E4", featuring: "", youtube_id: "eCBSTUS23E4", artist_id: 55, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Oh My", year: "2015", link: "https://www.youtube.com/watch?v=KuMF4EvYsuc", featuring: "", youtube_id: "KuMF4EvYsuc", artist_id: 57, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "All Around Feeling", year: "2013", link: "https://www.youtube.com/watch?v=_kSoAfNGmXU", featuring: "", youtube_id: "_kSoAfNGmXU", artist_id: 56, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "ILY2", year: "2016", link: "https://www.youtube.com/watch?v=eKAad4gvjvY", featuring: "", youtube_id: "eKAad4gvjvY", artist_id: 59, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Serve", year: "2015", link: "https://www.youtube.com/watch?v=8FCsp2Tlo4E", featuring: "TheCoolisMac", youtube_id: "8FCsp2Tlo4E", artist_id: 58, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "On Me", year: "2013", link: "https://www.youtube.com/watch?v=rZL8d25EiHQ", featuring: "", youtube_id: "rZL8d25EiHQ", artist_id: 60, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Fine$t", year: "2012", link: "https://www.youtube.com/watch?v=uzSIk-LqFhk", featuring: "", youtube_id: "uzSIk-LqFhk", artist_id: 60, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Cadie", year: "2012", link: "https://www.youtube.com/watch?v=aiyIyI9hoS0", featuring: "", youtube_id: "aiyIyI9hoS0", artist_id: 60, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Like Dat", year: "2016", link: "https://www.youtube.com/watch?v=6_mWyjJQxWg", featuring: "", youtube_id: "6_mWyjJQxWg", artist_id: 62, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Hello...", year: "2015", link: "https://www.youtube.com/watch?v=OxfiA4O9pLY", featuring: "", youtube_id: "OxfiA4O9pLY", artist_id: 63, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Light Skin Trick Daddy", year: "2014", link: "https://www.youtube.com/watch?v=-mBCaCe6QQw", featuring: "", youtube_id: "-mBCaCe6QQw", artist_id: 68, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Lean With The Sprite", year: "2013", link: "https://www.youtube.com/watch?v=fJJKj22knFM", featuring: "", youtube_id: "fJJKj22knFM", artist_id: 66, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Whitney Houston", year: "2013", link: "https://www.youtube.com/watch?v=3HLP6izBQ4g", featuring: "", youtube_id: "3HLP6izBQ4g", artist_id: 64, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Blunt After Blunt", year: "2011", link: "https://www.youtube.com/watch?v=rCt7ZxMoQyo", featuring: "", youtube_id: "rCt7ZxMoQyo", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Radio Song", year: "2012", link: "https://www.youtube.com/watch?v=QSX4vkHENLk", featuring: "", youtube_id: "QSX4vkHENLk", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Blueberry (Pills & Cocaine)", year: "2012", link: "https://www.youtube.com/watch?v=B-92qAjbGDo", featuring: "Darq E Freaker", youtube_id: "B-92qAjbGDo", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Druggys WitH Hoes Again", year: "2012", link: "https://www.youtube.com/watch?v=4oYwf5y9DFg", featuring: "Ab-Soul", youtube_id: "4oYwf5y9DFg", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "God Is Gangsta", year: "2016", link: "https://www.youtube.com/watch?v=4wZytWFm7x0", featuring: "", youtube_id: "4wZytWFm7x0", artist_id: 75, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "What They Want", year: "2014", link: "https://www.youtube.com/watch?v=5dBy9KEorjw", featuring: "2 Chainz", youtube_id: "5dBy9KEorjw", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Swimming Pools", year: "2013", link: "https://www.youtube.com/watch?v=B5YNiCfWC3A", featuring: "", youtube_id: "B5YNiCfWC3A", artist_id: 75, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Started From The Bottom", year: "2013", link: "https://www.youtube.com/watch?v=RubBzkZzpUA", featuring: "", youtube_id: "RubBzkZzpUA", artist_id: 45, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "This Is What You Came For", year: "2016", link: "https://www.youtube.com/watch?v=kOkQ4T5WO9E", featuring: "Calvin Harris", youtube_id: "kOkQ4T5WO9E", artist_id: 12, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "JIMBO", year: "2011", link: "https://www.youtube.com/watch?v=yx_irH7258Y", featuring: "", youtube_id: "yx_irH7258Y", artist_id: 37, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Lowlife", year: "2015", link: "https://www.youtube.com/watch?v=h_aAHXGH3sQ", featuring: "", youtube_id: "h_aAHXGH3sQ", artist_id: 52, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Count On Me", year: "2013", link: "https://www.youtube.com/watch?v=5VqcljJD9ZY", featuring: "", youtube_id: "5VqcljJD9ZY", artist_id: 52, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Untouchable Lucki", year: "2013", link: "https://www.youtube.com/watch?v=HOBP0khg5sU", featuring: "", youtube_id: "HOBP0khg5sU", artist_id: 52, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Noirse", year: "2013", link: "https://www.youtube.com/watch?v=fa-pgdsjNRE", featuring: "", youtube_id: "fa-pgdsjNRE", artist_id: 53, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Lord Knows", year: "2016", link: "https://www.youtube.com/watch?v=20FbPTAV-sU", featuring: "Joey Bada$$ ", youtube_id: "20FbPTAV-sU", artist_id: 51, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "AllI Need", year: "2014", link: "https://www.youtube.com/watch?v=t9eFdTpXGSk", featuring: "", youtube_id: "t9eFdTpXGSk", artist_id: 55, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Let Me Rap", year: "2014", link: "https://www.youtube.com/watch?v=vi0ckf7q4Vw", featuring: "", youtube_id: "vi0ckf7q4Vw", artist_id: 57, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Roses", year: "2015", link: "https://www.youtube.com/watch?v=1-qcz47h9zo", featuring: "", youtube_id: "1-qcz47h9zo", artist_id: 42, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "S.T.A.C.Y.", year: "2015", link: "https://www.youtube.com/watch?v=MWL5ersoSe8", featuring: "", youtube_id: "MWL5ersoSe8", artist_id: 59, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "2Much", year: "2016", link: "https://www.youtube.com/watch?v=U4LuEyZY92A", featuring: "", youtube_id: "U4LuEyZY92A", artist_id: 60, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Reason", year: "2014", link: "https://www.youtube.com/watch?v=im9UzhOxVlI", featuring: "", youtube_id: "im9UzhOxVlI", artist_id: 27, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Worn", year: "2015", link: "https://www.youtube.com/watch?v=NyQdisFFJas", featuring: "", youtube_id: "NyQdisFFJas", artist_id: 27, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Cell Boomin", year: "2015", link: "https://www.youtube.com/watch?v=feFKeFMUS60", featuring: "Father", youtube_id: "feFKeFMUS60", artist_id: 64, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Witness", year: "2016", link: "https://www.youtube.com/watch?v=lHitmmi2VdY", featuring: "Clams Casino", youtube_id: "lHitmmi2VdY", artist_id: 32, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Retribution", year: "2015", link: "https://www.youtube.com/watch?v=xhSX7tyB83k", featuring: "", youtube_id: "xhSX7tyB83k", artist_id: 67, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Big Worm", year: "2016", link: "https://www.youtube.com/watch?v=7Cus2UvzlvU", featuring: "", youtube_id: "7Cus2UvzlvU", artist_id: 64, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Harambe", year: "2016", link: "https://www.youtube.com/watch?v=e7n2VC45-88", featuring: "", youtube_id: "e7n2VC45-88", artist_id: 69, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Watch Out", year: "2016", link: "https://www.youtube.com/watch?v=cG21b8Kx2DI", featuring: "", youtube_id: "cG21b8Kx2DI", artist_id: 70, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Rewind", year: "2015", link: "https://www.youtube.com/watch?v=py6PgXq0yDM", featuring: "", youtube_id: "py6PgXq0yDM", artist_id: 72, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Gold Mouth Piranha ", year: "2015", link: "https://www.youtube.com/watch?v=5Edgxc573-M", featuring: "", youtube_id: "5Edgxc573-M", artist_id: 73, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Green Ranger", year: "2016", link: "https://www.youtube.com/watch?v=zmcKyaoDTFk", featuring: "", youtube_id: "zmcKyaoDTFk", artist_id: 73, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "The Song That Never Ends (Huzzah Part 2)", year: "2011", link: "https://www.youtube.com/watch?v=nzcFjJSgWfE", featuring: "Heron", youtube_id: "nzcFjJSgWfE", artist_id: 73, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Nightfall At The Thames", year: "2013", link: "https://www.youtube.com/watch?v=OQknj92e7cw", featuring: "", youtube_id: "OQknj92e7cw", artist_id: 73, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Grown Up", year: "2012", link: "https://www.youtube.com/watch?v=NHfWY0is3rE", featuring: "", youtube_id: "NHfWY0is3rE", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "DIP", year: "2013", link: "https://www.youtube.com/watch?v=CZa2lY9CFyM", featuring: "", youtube_id: "CZa2lY9CFyM", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Monopoly", year: "2011", link: "https://www.youtube.com/watch?v=Nj0jiEIyT24", featuring: "", youtube_id: "Nj0jiEIyT24", artist_id: 74, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "THere He Go", year: "2012", link: "https://www.youtube.com/watch?v=KnnYiW5dnhQ", featuring: "", youtube_id: "KnnYiW5dnhQ", artist_id: 24, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "i", year: "2014", link: "https://www.youtube.com/watch?v=8aShfolR6w8", featuring: "", youtube_id: "8aShfolR6w8", artist_id: 75, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Jealousy", year: "2015", link: "https://www.youtube.com/watch?v=bt-IM0XJYOo", featuring: "", youtube_id: "bt-IM0XJYOo", artist_id: 87, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Guess Who (Fuckin Yo Bitch)", year: "2013", link: "https://www.youtube.com/watch?v=zplGBqFFPRo", featuring: "", youtube_id: "zplGBqFFPRo", artist_id: 88, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Poppin", year: "2016", link: "https://www.youtube.com/watch?v=haUKYogqFw8", featuring: "", youtube_id: "haUKYogqFw8", artist_id: 94, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Koi", year: "2015", link: "https://www.youtube.com/watch?v=aUBzGKpHGAY", featuring: "", youtube_id: "aUBzGKpHGAY", artist_id: 95, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "1 Bad B*tch", year: "2014", link: "https://www.youtube.com/watch?v=XPbpl35uX8w", featuring: "Ten Ven", youtube_id: "XPbpl35uX8w", artist_id: 97, featuring_2: "Ripley", featuring_3: "", featuring_4: ""},
  {title: "The Big Big Beat", year: "2016", link: "https://www.youtube.com/watch?v=PXUfBxMbC3A", featuring: "", youtube_id: "PXUfBxMbC3A", artist_id: 98, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Wrath of the Guided NuAgeSyndicate", year: "2015", link: "https://www.youtube.com/watch?v=P-c8ggWHYk4", featuring: "", youtube_id: "P-c8ggWHYk4", artist_id: 105, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Live-ation", year: "2013", link: "https://www.youtube.com/watch?v=eGf0KetI6Ls", featuring: "", youtube_id: "eGf0KetI6Ls", artist_id: 106, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Little Bit of This", year: "2016", link: "https://www.youtube.com/watch?v=qkxEKumTj08", featuring: "GTA", youtube_id: "qkxEKumTj08", artist_id: 13, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Blue Lights", year: "2016", link: "https://www.youtube.com/watch?v=i59Klb0S1Uw", featuring: "", youtube_id: "i59Klb0S1Uw", artist_id: 108, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "95 Til Infinity", year: "2013", link: "https://www.youtube.com/watch?v=N1yGG8jMSTI", featuring: "", youtube_id: "N1yGG8jMSTI", artist_id: 48, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Chasing Faith x Rain Dance x Allusions", year: "2015", link: "https://www.youtube.com/watch?v=rKbvHYkEyng", featuring: "", youtube_id: "rKbvHYkEyng", artist_id: 14, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Face - Off", year: "2012", link: "https://www.youtube.com/watch?v=88zEFqJjPh8", featuring: "", youtube_id: "88zEFqJjPh8", artist_id: 118, featuring_2: "", featuring_3: "", featuring_4: ""},
  {title: "Dolce & Gabbana", year: "2013", link: "https://www.youtube.com/watch?v=JxLS-cpgbe0", featuring: "", youtube_id: "JxLS-cpgbe0", artist_id: 120, featuring_2: "", featuring_3: "", featuring_4: ""}
])
